show databases;
use foody1;
show tables;
insert into Customers values('Harshal',1,'harsh123',9876543212,'Maharashtra'),('Hari',2,'hari123',9567890987,'Chennai'),('Kartik',3,'kartik1223',8765432123,'Jammu'),('sayan',4,'sayan123',9087654345,'Kolkata');
alter table Customers add Email_Id varchar(15) not null;
alter table Customers add Customer_age int;
desc Customers;
set SQL_SAFE_UPDATES=0;
update Customers set Email_Id='harsh@gmail.com' where Cust_id=1 ;
update Customers set Email_Id='hari@gmail.com' where Cust_id=2;
update Customers set Email_Id='kart@gmail.com' where Cust_id=3 ;
update Customers set Email_Id='sayan@gmail.com' where Cust_id=4 ;
select * from Customers where Address='Maharashtra' AND Cust_id <=1;
select * from Customers where Address='Maharashtra' OR Address='Jammu' ;
select * from Customers where (Address='Maharashtra' AND Cust_id <=1) OR (Cust_id < 6);
insert into Customers values('Sahil',5,'sahil123',9876343212,'Maharashtra','sahil@gmail.com',21),('Mahesh',6,'mahesh123',9556890987,'Chennai','mahi@gmail.com',23),('Ram',7,'Ram1223',8768932123,'kashmir','ram@gmail.com',34),('Aniket',8,'Andi23',9089354345,'Delhi','andi@gmail.com',43);
update Customers set Customer_age=22 where Cust_id=1 ;
update Customers set Customer_age=20 where Cust_id=2 ;
update Customers set Customer_age=26 where Cust_id=3 ;
update Customers set Customer_age=24 where Cust_id=4 ;
select * from Customers where Address='Maharashtra' OR Address='Jammu' ;
select distinct address from Customers;
update Customers set Address= 'Jammu' where Cust_id=2;
alter table Customers Change column Email_Id Email_Id varchar(50) not null after Address;
select distinct Address from Customers where Address='Maharashtra';
select * from Customers where Address='Jammu' order by Cust_name ASC;
select * from Customers where Cust_Id <7 order by Cust_name DESC;
select Address,COUNT(Address) as 'Address Count ' from Customers group by  Address;
alter table Customers add Product_quantity bigint ;
update Customers set Product_quantity=1000  where Cust_id=1 ;
update Customers set Product_quantity=1120  where Cust_id=2 ;
update Customers set Product_quantity=1400  where Cust_id=3 ;
update Customers set Product_quantity=1670  where Cust_id=4 ;
update Customers set Product_quantity=1540  where Cust_id=5 ;
update Customers set Product_quantity=2340  where Cust_id=6 ;
update Customers set Product_quantity=1560  where Cust_id=7 ;
update Customers set Product_quantity=1560  where Cust_id=8 ;
select Cust_name,Customer_age from Customers where Customer_age in (select max(Customer_age) from Customers);
select Cust_name,Customer_age from Customers order by Customer_age ASC limit 1;
select * from  Customers where Cust_name LIKE 'a%';
use foody1;
desc Customers;
select * from Customers where Address not LIKE '%a';

select * from Customers where Cust_Id  between 1 and 8;
alter  table Customers add DOB varchar(30);
update Customers set DOB='1997-01-12'  where Cust_id=1 ;
update Customers set DOB='1995-06-04' where Cust_id=2 ;
update Customers set DOB='1994-05-12'  where Cust_id=3 ;
update Customers set DOB='1999-07-11'  where Cust_id=4 ;
update Customers set DOB='1998-05-09'  where Cust_id=5 ;
update Customers set DOB='1994-04-08'  where Cust_id=6 ;
update Customers set DOB='1996-11-04'  where Cust_id=7 ;
update Customers set DOB='1992-12-02'  where Cust_id=8 ;
alter table Customers change DOB DOB varchar(30) after Customer_password ;
alter table Customers drop DOB;
select * from Customers;
select * from Vendors;

